//USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_SESSION_DATA = "SET_SESSION_DATA";
export const LOADING_USER = "LOADING_USER";

//UI REDUCER TYPES
export const SET_GENERAL_ERRORS = "SET_ERRORS";
export const CLEAR_GENERAL_ERRORS = "CLEAR_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

//DATA REDUCER TYPES
