//USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_SESSION_DATA = "SET_SESSION_DATA";
export const LOADING_USER = "LOADING_USER";
export const STOP_LOADING_USER = "STOP_LOADING_USER";

//UI REDUCER TYPES
export const SET_GENERAL_ERRORS = "SET_ERRORS";
export const CLEAR_GENERAL_ERRORS = "CLEAR_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

//DATA REDUCER TYPES
export const SET_ADMINS = "SET_ADMINS";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_DATA = "STOP_LOADING_DATA";
export const SET_UPDATED_ADMIN = "SET_UPDATED_ADMIN";
export const SET_NEW_ADMIN_LINK = "SET_NEW_ADMIN_LINK";
export const CLEAR_NEW_ADMIN_LINK = "CLEAR_NEW_ADMIN_LINK";
export const SET_ORIENTATION_OVERVIEW = "SET_ORIENTATION_OVERVIEW";
export const UPDATE_ORIENTATION_OVERVIEW_TITLE =
  "UPDATE_ORIENTATION_OVERVIEW_TITLE";
export const SET_ORIENTATION_PAGES = "SET_ORIENTATION_PAGES";
export const SET_ORIENTATION_PAGE_TITLE = "SET_ORIENTATION_PAGE_TITLE";
export const SET_ORIENTATION_PAGE_HEADER = "SET_ORIENTATION_PAGE_HEADER";
export const SET_ORIENTATION_PAGE_CONTENT = "SET_ORIENTATION_PAGE_CONTENT";
export const SET_SUBCONTENT_TITLE = "SET_SUBCONTENT_TITLE";
export const SET_SUBCONTENT_CONTENT = "SET_SUBCONTENT_CONTENT";
export const SET_SUBCONTENT_IMAGE = "SET_SUBCONTENT_IMAGE";
export const DELETE_SUBCONTENT = "DELETE_SUBCONTENT";
export const DELETE_ORIENTATION_PAGE = "DELETE_ORIENTATION_PAGE";
export const ADD_ORIENTATION_PAGE = "ADD_ORIENTATION_PAGE";
export const ADD_ORIENTATION_POST = "ADD_ORIENTATION_POST";
