//USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_SESSION_DATA = "SET_SESSION_DATA";
export const LOADING_USER = "LOADING_USER";
export const STOP_LOADING_USER = "STOP_LOADING_USER";

//UI REDUCER TYPES
export const SET_GENERAL_ERRORS = "SET_ERRORS";
export const CLEAR_GENERAL_ERRORS = "CLEAR_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

//DATA REDUCER TYPES
export const SET_ADMINS = "SET_ADMINS";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const LOADING_DATA = "LOADING_UI";
export const STOP_LOADING_DATA = "STOP_LOADING_UI";
export const SET_UPDATED_ADMIN_ROLE = "SET_UPDATED_ADMIN_ROLE";
export const SET_NEW_ADMIN_LINK = "SET_NEW_ADMIN_LINK";
export const CLEAR_NEW_ADMIN_LINK = "CLEAR_NEW_ADMIN_LINK";
